# version: 2.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$docker_context\
$nix_shell\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$kubernetes\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$character"""

right_format = ""

[character]
format = "$symbol "
success_symbol = "[❯](bold italic bright-yellow)"
error_symbol = "[❯](italic purple)"
vimcmd_symbol = "[](italic dimmed green)"

[username]
style_user = "bright-yellow bold"
style_root = "purple bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname]($style) "
style = "bold dimmed green"
disabled = true

[directory]
#home_symbol = "󰋜"
home_symbol = "~"
truncation_length = 0
truncate_to_repo = false
read_only = " 󰌾"
use_os_path_sep = true
style = "cyan bold"
format = "in [$path]($style)[$read_only]($read_only_style) "
repo_root_style = 'cyan bold'
repo_root_format = 'in [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
format = "on [ $branch(:$remote_branch)]($style) "
symbol = ""
style = "bold purple"
truncation_symbol = "…"
truncation_length = 20
only_attached = false

[git_commit]
format = "on [\\($hash$tag\\)]($style) "
style = "bold green"
only_detached = true
tag_symbol = " 󰓹 "
tag_disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bright-black"

[git_metrics]
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = 'bold green'
deleted_style = 'bold red'
disabled = false

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"
conflicted = "󰞇 "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[package]
format = "is [󰏗 $version]($style) "
style = "bold 208"
display_private = false

[deno]
format = "via [$symbol$version]($style) "
version_format = "${raw}"
symbol = "󰛦 "
style = "green bold"

[lua]
format = "via [$symbol$version]($style) "
version_format = "${raw}"
symbol = "󰢱 "
style = "bold blue"

[nodejs]
format = "via [$symbol$version]($style) "
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []
symbol = "󰎙 "
style = "bold green"

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "󰌠 "
version_format = "${raw}"
style = "yellow bold"

[ruby]
format = "via [$symbol$version]($style) "
symbol = "󰴭 "
version_format = "${raw}"
style = "bold red"

[rust]
format = "via [$symbol$version]($style) "
symbol = "󱘗 "
version_format = "${raw}"
style = "bold red"

[swift]
format = "via [$symbol$version]($style) "
symbol = "󰛥 "
style = "bold 202"
version_format = "${raw}"

[aws]
disabled = true
format = "on [$symbol$profile $region]($style) "
style = "bold yellow"
symbol = "󰸏 "

[buf]
symbol = "󰘨 "
format = "via [$symbol$version]($style) "

[c]
format = "via [$symbol$version(-$name)]($style) "
symbol = " "

[cpp]
format = "via [$symbol$version(-$name)]($style) "
symbol = " "

[cmake]
format = "via [$symbol$version]($style) "
symbol = "󰔷 "

[conda]
symbol = "󰔶 "
format = "via [$symbol$environment]($style) "

[pixi]
symbol = "󰔶 "
format = "via [$symbol$version ($environment)]($style) "

[dart]
symbol = " "
format = "via [$symbol$version]($style) "

[docker_context]
symbol = "󰡨 "
format = "via [$symbol$context]($style) "

[elixir]
symbol = " "
format = "via [$symbol$version OTP $otp_version]($style) "

[elm]
symbol = " "
format = "via [$symbol$version]($style) "

[erlang]
symbol = " "
format = "via [$symbol$version]($style) "

[golang]
symbol = "󰟓 "
format = "via [$symbol$version]($style) "

[haskell]
symbol = "󰲒 "
format = "via [$symbol$version]($style) "

[helm]
symbol = "󰠳 "
format = "via [$symbol$version]($style) "

[java]
symbol = "󰬷 "
format = "via [$symbol$version]($style) "

[julia]
symbol = "󰘧 "
format = "via [$symbol$version]($style) "

[kotlin]
symbol = "󱈙 "
format = "via [$symbol$version]($style) "

[gradle]
symbol = "󰓾 "
format = "via [$symbol$version]($style) "

[memory_usage]
symbol = "󰍛 "
format = "via [$symbol${ram}( ${swap})]($style) "

[nim]
symbol = "󰆥 "
format = "via [$symbol$version]($style) "

[nix_shell]
style = 'bold blue'
symbol = '󱄅 '
format = 'via [$symbol$state( \($name\))]($style) '
impure_msg = 'impure'
pure_msg = 'pure'

[ocaml]
symbol = " "
format = "via [$symbol$version]($style) "

[perl]
symbol = " "
format = "via [$symbol$version]($style) "

[php]
symbol = "󰌟 "
format = "via [$symbol$version]($style) "

[terraform]
symbol = "󱁢 "
format = "via [$symbol$version]($style) "

[zig]
symbol = "󰰛 "
format = "via [$symbol$version]($style) "

[spack]
symbol = "󰏗 "
format = "via [$symbol$environment]($style) "

[status]
format = "[$symbol$status]($style) "
disabled = true

[os]
format = "[$symbol]($style) "
disabled = true

[sudo]
format = "[as $symbol]($style) "
symbol = "󱆀 "
style = "bold blue"
disabled = false

[cmd_duration]
format = "took [$duration]($style) "
style = "bold yellow"
min_time = 2000

[jobs]
format = "[$symbol$number]($style) "
style = "bold blue"
symbol = "󰜎 "
threshold = 1

[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "

[[battery.display]]
threshold = 30
style = "bold red"

[time]
disabled = false
format = "at [$time]($style) "
time_format = "%R"
style = "bold dimmed white"

[shell]
format = "[$indicator]($style) "
bash_indicator = "bsh"
fish_indicator = "fsh"
zsh_indicator = "zsh"
disabled = true

[line_break]
disabled = false

[kubernetes]
symbol = "󱃾 "
format = "on [$symbol$context( \\($namespace\\))]($style) "
disabled = false
